# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Install uv
FROM python:3.12-slim

# Install tini and Node.js (for mcp-proxy)
RUN apt-get update && \
    apt-get install -y --no-install-recommends tini curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

# Install mcp-proxy globally
RUN npm install -g mcp-proxy

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# Change the working directory to the `app` directory
WORKDIR /app

# Copy the lockfile and `pyproject.toml` into the image
COPY uv.lock /app/uv.lock
COPY pyproject.toml /app/pyproject.toml

# Install dependencies
RUN uv sync --frozen --no-install-project

# Copy the project into the image
COPY . /app

# Sync the project
RUN uv sync --frozen

EXPOSE 8080

# Run mcp-proxy in front of the email server
CMD mcp-proxy --port ${PORT:-8080} -- uv run mcp-email-server stdio
